version: "3"

services:

  server:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        - NGINX_HOST=${NGINX_HOST}
    container_name: server
    ports:
      - 80:80
    env_file:
      - ".env"
    depends_on:
      - php
      - db
    volumes:
      - .:/app

  db:
      image: mysql:8.0.3
      container_name: ${MYSQL_HOST}
      restart: always
      ports:
        - 3306:3306
      env_file:
        - ".env"
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  php:
    build: .docker/php-fpm
    container_name: app
    environment:
        XDEBUG_CONFIG: remote_host=172.18.0.1
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db

  composer:
    image: "composer"
    volumes:
        - "./web/app:/app"
    command: install